### ISSUE TITLE
Could you please also give the command of running the sds?

### ISSUE THREAD

**Issue by cwchenwang** [yuanzhi-zhu/prolific_dreamer2d#1]

**Comment by yuanzhi-zhu** [comment]
Hi, thank you for your interest, you can simply set generation_mode as 'sds'.

I will update a brief introduction to the parameters soon in readme.

**Comment by cwchenwang** [comment]
This is what I get with sds.
<img width="839" alt="image" src="https://github.com/yuanzhi-zhu/prolific_dreamer2d/assets/23579918/ec86a95d-9eba-44cb-8f19-d290f72938f8">

**Comment by yuanzhi-zhu** [comment]
Sorry, I forget to mention that you have to change the cfg to 100 for further comparison.

This result for me makes sense by comparing the Figure 3 (a) in the original paper :p

**Comment by yuanzhi-zhu** [comment]
HI @cwchenwang , readme has been updated, please let me know if you have any further questions

**Comment by cwchenwang** [comment]
Thank you
