### ISSUE TITLE
replacement of sds loss

### ISSUE THREAD

**Issue by VLadImirluren** [yuanzhi-zhu/prolific_dreamer2d#10]
I want to try dreamfusion's simple replacement of vsd loss, can I use the code in this project directly, because it is a 2d prolificdreamer, do I need to make any modifications? please give me some guidance

**Comment by yuanzhi-zhu** [comment]
Yes @VLadImirluren, you can test SDS directly from the command line as mentioned in the readme https://github.com/yuanzhi-zhu/prolific_dreamer2d#sds-command-line

**Comment by VLadImirluren** [comment]
> Yes @VLadImirluren, you can test SDS directly from the command line as mentioned in the readme https://github.com/yuanzhi-zhu/prolific_dreamer2d#sds-command-line

oh thanks.
But I mean I want to use vsd in 3d space, the implementation of threestudio is too complicated, I want to test myself on dreamfusion, to evaluate the vsd loss by doing this ablation study

**Comment by yuanzhi-zhu** [comment]
@VLadImirluren unfortunately, this repo only serves as 2D toy experiments to help understand VSD.

**Comment by VLadImirluren** [comment]
@yuanzhi-zhu All right....I get it. thanks!
