### ISSUE TITLE
Code question

### ISSUE THREAD

**Issue by Gynjn** [yuanzhi-zhu/prolific_dreamer2d#12]
First, thank you for the great implementation!

https://github.com/yuanzhi-zhu/prolific_dreamer2d/blob/main/model_utils.py#L242

Could you describe why the lora scale "0" is depends on lora_v? 

<img width="739" alt="screenshot" src="https://github.com/yuanzhi-zhu/prolific_dreamer2d/assets/106458325/3112f05f-6e90-4c77-b6c7-8cd3f6b2497d">

**Comment by yuanzhi-zhu** [comment]
Sorry for the confusion.

When setting `lora_v` == True, we are using two separate models for $\theta$ model and $\phi$ model.

And this `unet_cross_attention_kwargs` is only meant to be used when we use one model for both $\theta$ and $\phi$ models (see comment: https://github.com/yuanzhi-zhu/prolific_dreamer2d/blob/main/model_utils.py#L245).
