### ISSUE TITLE
Classifer-free guidance

### ISSUE THREAD

**Issue by QianyiWu** [yuanzhi-zhu/prolific_dreamer2d#13]
Hi,

Thanks for your awesome implementation. I have one question regarding the CFG guidance. Dose [this line](https://github.com/yuanzhi-zhu/prolific_dreamer2d/blob/69710cc54ed9f39e3c720f8629aab1b1d132c084/model_utils.py#L183C33-L183C33) should be
```
noise_pred = noise_pred_text + guidance_scale * (noise_pred_text - noise_pred_uncond)
```

**Comment by yuanzhi-zhu** [comment]
Hi, I just followed the practice in diffuser.

Indeed, the expression you provided is almost the equivalent but with a -1 cfg (you can plus and then subtract the unconditional term).

**Comment by QianyiWu** [comment]
Thanks for pointing out the diffuser implementation reference. It solved my concerns :)
