### ISSUE TITLE
Question: About the calculation of x0

### ISSUE THREAD

**Issue by luocfprime** [yuanzhi-zhu/prolific_dreamer2d#14]
When `save_x0=True`, the following code is used to compute x0.

```python
pred_latents = scheduler.step(noise_pred-noise_pred_phi+noise, t, noisy_latents).pred_original_sample.to(dtype).clone().detach()
```

May I ask the rationale behind this formula? To my understanding, to compute $\hat{x_0}$ via pretrained model, one should use:

```
pred_latents = scheduler.step(noise_pred, t, noisy_latents).pred_original_sample.to(dtype).clone().detach()
```

The code which I'm referring to is https://github.com/yuanzhi-zhu/prolific_dreamer2d/blob/e2ffc938d18229ef57a1ad9af7b297275b4d4fbb/prolific_dreamer2d.py#L458

What's the mathematical meaning of calculating `noise_pred-noise_pred_phi+noise`?

Thanks!

**Comment by yuanzhi-zhu** [comment]
Hi Chaofan
Good catch!!
In short, this is an analog to SDS, to calculate the effective $\hat\epsilon$
Maybe the following two slides can help you to better understand the motivation behind the code:
![image](https://github.com/yuanzhi-zhu/prolific_dreamer2d/assets/24802044/c6a60773-89f8-4fd6-97ec-49081cd43bce)
![image](https://github.com/yuanzhi-zhu/prolific_dreamer2d/assets/24802044/a7b8f035-e64d-443f-b972-76546209943d)

**Comment by luocfprime** [comment]
Hi, thanks for replying!

Now I get it. The reparameterized  noise prediction $\hat{\epsilon} - \hat{\epsilon_\phi} + \epsilon$ serves as the actual pseudo ground truth that guides the training of $x_s$.

This is an interesting perspective indeed, thanks for sharing!
