### ISSUE TITLE
About code running issues

### ISSUE THREAD

**Issue by muzimudong** [yuanzhi-zhu/prolific_dreamer2d#16]
Hello, after I installed all the required packages according to the guide, I got an error ：
“OSError: CompVis/stable-diffusion-v1-4 does not appear to have a file named config.json ”
that will be reported during the operation. What should I do

**Comment by yuanzhi-zhu** [comment]
do you have the correct diffusers installed?

**Comment by muzimudong** [comment]
Hello, I am a beginner. There does not appear to be a specific version of diffusers required in requirements.txt




---Original---
From: "Yuanzhi ***@***.***&gt;
Date: Sat, Nov 23, 2024 05:37 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [yuanzhi-zhu/prolific_dreamer2d] About code running issues (Issue#16)




 
do you have the correct diffusers installed?

**Comment by yuanzhi-zhu** [comment]
did you config the environment with
```pip install -r requirements.txt``` ?

**Comment by muzimudong** [comment]
yes,i do



---Original---
From: "Yuanzhi ***@***.***&gt;
Date: Sat, Nov 23, 2024 19:36 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [yuanzhi-zhu/prolific_dreamer2d] About code running issues (Issue#16)




 
did you config the environment with
 pip install -r requirements.txt ?

**Comment by yuanzhi-zhu** [comment]
I checked and it work well on my machine, could you show me more error message?
You can also try to download the model into a local folder then use it.

**Comment by muzimudong** [comment]
Thank you very much. After I downloaded the model to local deployment, it was able to run successfully.




夜空中最亮的星
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yuanzhi-zhu/prolific_dreamer2d"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年11月24日(星期天) 上午7:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yuanzhi-zhu/prolific_dreamer2d] About code running issues (Issue #16)





 
I checked and it work well on my machine, could you show me more error message?
 You can also try to download the model into a local folder then use it.
