### ISSUE TITLE
Code error

### ISSUE THREAD

**Issue by muzimudong** [yuanzhi-zhu/prolific_dreamer2d#17]
Hello, I changed the parameter '--generation model' from 'sds' to 'vsd', the code reported "TypeError:__init__() got an unexpected keyword argument 'hidden_size", How can I fix this

**Comment by yuanzhi-zhu** [comment]
Could you provide the full error message?

**Comment by muzimudong** [comment]
The full error message as follows:
![{A5F85E1C-6661-4d4a-BB5E-4D1C492F4B60}](https://github.com/user-attachments/assets/c8d2557b-423e-4ea6-b18e-a5cac91902d7)

**Comment by yuanzhi-zhu** [comment]
this look like a diffusers version problem, which I have no idea.
If I create a new environment and correctly install all the packages my code works fine

**Comment by muzimudong** [comment]
Hi, if I am going to use vsd should I use stable-diffusion-2-1 base instead of stable-diffusion-v1-4，right?

**Comment by yuanzhi-zhu** [comment]
I think both will work

**Comment by muzimudong** [comment]
Hello, after I set the parameters of the VSD command line and run it, a new problem occurred. As shown in the following figure, there was a problem of dimension mismatch, but no error was reported after generation_mode was changed to sds. I printed out the dimensions of “latent_model_input” and “text_embeddings” in sds and vsd modes respectively. The parameter dimensions are the same in both modes. How can I solve this problem
![image](https://github.com/user-attachments/assets/6652b088-a564-48ae-ad6f-042e1cd223da)
![image](https://github.com/user-attachments/assets/4f89073a-4dcb-4ccc-8d2c-6a39989857a7)

**Comment by yuanzhi-zhu** [comment]
@muzimudong can you provide the command line to reproduce your problem?

**Comment by muzimudong** [comment]
The command line as follows:
python prolific_dreamer2d.py \
        --num_steps 500 --log_steps 50 \
        --lr 0.03 --phi_lr 0.0001 --use_t_phi true \
        --model_path 'runwayml/stable-diffusion-v1-5' \
        --loss_weight '1m_alphas_cumprod' \
        --t_schedule random --generation_mode 'vsd' \
        --phi_model 'lora' --lora_scale 1. \
        --prompt "a photograph of an astronaut riding a horse" \
        --height 512 --width 512 --batch_size 1 --guidance_scale 7.5 \
        --log_progress true --save_x0 true --save_phi_model true \

**Comment by muzimudong** [comment]
text_embeddings is 154x768, but i don‘t find a parameter with dimension 320x4

**Comment by yuanzhi-zhu** [comment]
Still, I can not reproduce this error
are you sure you've installed the dependencies via `pip install -r requirements.txt`?

**Comment by muzimudong** [comment]
I am sure I've installed the dependencies via pip install -r requirements.txt



---Original---
From: "Yuanzhi ***@***.***&gt;
Date: Sun, Dec 22, 2024 17:35 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [yuanzhi-zhu/prolific_dreamer2d] Code error (Issue #17)




 
Still, I can not reproduce this error
 are you sure you've installed the dependencies via pip install -r requirements.txt?

**Comment by yuanzhi-zhu** [comment]
can you try to create a **new** environment and repeat?

**Comment by muzimudong** [comment]
Ok, I'll try it later. Thank you so much for your patience in answering this beginner's question




---Original---
From: "Yuanzhi ***@***.***&gt;
Date: Sun, Dec 22, 2024 17:46 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [yuanzhi-zhu/prolific_dreamer2d] Code error (Issue #17)




 
can you try to create a new environment and repeat?

**Comment by muzimudong** [comment]
Hello, the diffusers in requirements.txt diffusers@git+https://github.com/huggingface/diffusers@1994dbcb5e62bd8d0c60e5d5d6bf4b580653c74c in ., This link is no longer available. What is your diffusers version

**Comment by yuanzhi-zhu** [comment]
for me, I can just install this version of diffusers with 
`pip install diffusers@git+https://github.com/huggingface/diffusers@1994dbcb5e62bd8d0c60e5d5d6bf4b580653c74c`

you can also try `pip install diffusers==0.17.0.dev0`

**Comment by muzimudong** [comment]
Thank you very much,after intalling&nbsp;diffusers==0.17.0,i&nbsp;successfully ran the vsd
&nbsp;


夜空中最亮的星
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yuanzhi ***@***.***&gt;; 
发送时间: 2024年12月24日(星期二) 凌晨2:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [yuanzhi-zhu/prolific_dreamer2d] Code error (Issue #17)














 
for me, I can just install this version of diffusers with
 pip install ***@***.******@***.***
 
you can also try pip install diffusers==0.17.0.dev0
