### ISSUE TITLE
What is the version of diffusers?

### ISSUE THREAD

**Issue by Quantuman134** [yuanzhi-zhu/prolific_dreamer2d#3]
The version of diffusers in my environment is 0.14.0, and there is not the package diffusers.models.attention_processor. I also look up the newest version of diffusers 0.17.0, there is not this package too.

**Comment by yuanzhi-zhu** [comment]
Hi,
Have you tried to install it according to the requirement.txt?
Just new an venv and pip -r install requirement.txt.

**Comment by Quantuman134** [comment]
Thanks! I work out and the diffusers with version of 0.17.1 is feasible.
