### ISSUE TITLE
Why use DDIM scheduler?

### ISSUE THREAD

**Issue by jhq1234** [yuanzhi-zhu/prolific_dreamer2d#5]
Hi, Thanks for uploading your work. I really enjoy this!

I have a question about your code.
In prolific_dreamer2d.py(https://github.com/yuanzhi-zhu/prolific_dreamer2d/blob/main/prolific_dreamer2d.py#L163), you use DDIM scheduler for scheduling.
Can I ask why you use DDIM scheduler, not DDPM or others?
Thanks!

**Comment by yuanzhi-zhu** [comment]
This is rather a handwavy choice, you can also try the other schedulers.
As long as we can get the correct precious state $x_{t-1}$ and predicted $x_0$, the specific scheduler used should not significantly impact the results.

**Comment by jhq1234** [comment]
@yuanzhi-zhu 
Thank you for your quick response!
I didn't know you'd answer quickly like this, I understand that scheduler choice part! Thanks!

Have you conducted an experiment on a single particle (One single image)?

**Comment by yuanzhi-zhu** [comment]
By default, we are using a single particle (see the figure in readme).
