### ISSUE TITLE
DeepFloyd IF

### ISSUE THREAD

**Issue by YoujiaZhang** [yuanzhi-zhu/prolific_dreamer2d#8]
Can you provide a version of DeepFloyd IF? Thank you very much!

**Comment by yuanzhi-zhu** [comment]
Unfortunately, currently I do not have time to do that (also I have no experience with DeepFloyd IF).

But PR is welcomed!!

**Comment by yuanzhi-zhu** [comment]
Hi @YoujiaZhang 

In the most recent update, I added code that utilizes DeepFloyd IF for the diffusion model.

However, there's still room for improvement in its performance.......
