### ISSUE TITLE
What's the differences between VSD command line multiple particles and VSD command line?

### ISSUE THREAD

**Issue by VLadImirluren** [yuanzhi-zhu/prolific_dreamer2d#9]
thanks for your greate implementation!

**Comment by VLadImirluren** [comment]
there is a bug in VSD command line multiple particles:
Traceback (most recent call last):
  File "prolific_dreamer2d.py", line 539, in <module>
    main()
  File "prolific_dreamer2d.py", line 489, in main
    save_image((image/2+0.5).clamp(0, 1), f'{args.work_dir}/{image_name}_image_step{step}_t{t.item()}.png')
UnboundLocalError: local variable 'image' referenced before assignment

**Comment by yuanzhi-zhu** [comment]
Hi @VLadImirluren 
thank you for your interest and bug report
1. in VSD command line, we use one particle by default.
2. A quick fix has been made.

**Comment by VLadImirluren** [comment]
thanks! @yuanzhi-zhu
